### ISSUE TITLE
Fhirpath function toString() is not supported

### ISSUE THREAD

**Issue by pavlushkin** [beda-software/sdc-qrf#13]
### That works
```yaml
        choiceColumn:
          - path: "priceOverride.value"
            forDisplay: true
```

### That throws an error
```yaml
        choiceColumn:
          - path: "priceOverride.value.toString() + 'x'"
            forDisplay: true
```
