### ISSUE TITLE
Search answer in nested groups for enableWhen

### ISSUE THREAD

**Issue by ruscoder** [beda-software/sdc-qrf#18]
Use case
```
resourceType: Questionnaire
id: test-repeatable-group-1
status: draft
item:
  - linkId: group
    type: group
    repeats: true
    item:
      - linkId: nested
        type: group
        item:
          - linkId: first
            type: string
            text: first
      - linkId: second
        type: string
        text: second
        enableWhen:
          - question: first
            operator: =
            answerString: ok
      
meta:
  profile:
    - https://emr-core.beda.software/StructureDefinition/fhir-emr-questionnaire
  extension:
    - url: ex:createdAt
      valueInstant: '2025-05-29T15:22:50.345605Z'
```

It does not work, however it works if answers on the same level.
