### ISSUE TITLE
enabledWhen in repeatable groups outside group always relies on the first item

### ISSUE THREAD

**Issue by ruscoder** [beda-software/sdc-qrf#20]
Example:
```yaml
resourceType: Questionnaire
id: test-repeatable-group-1
status: draft
item:
  - linkId: group
    type: group
    repeats: true
    item:
      - linkId: first
        type: string
        text: first
  - linkId: second
    type: string
    text: second
    enableWhen:
      - question: first
        operator: =
        answerString: ok
      
meta:
  profile:
    - https://emr-core.beda.software/StructureDefinition/fhir-emr-questionnaire
  extension:
    - url: ex:createdAt
      valueInstant: '2025-05-29T15:22:50.345605Z'
```

1. Add two group items
2. Fill the first with 'not ok'
3. Fill the second with 'ok'
4. The conditional item is not shown
