### ISSUE TITLE
Add  x-fhir-query support for item.variable

### ISSUE THREAD

**Issue by ruscoder** [beda-software/sdc-qrf#9]
According to the [specification](https://build.fhir.org/ig/HL7/sdc/expressions.html) variable section:
> The content type of a variable can be pretty much anything. It can be a collection or an individual item. It can be a simple element, a complex type, a resource or even a Bundle of resources.

If it's supported in sdc-qrf, we will be able to do:
```yaml
item:
- linkid: selected-patient-ref
  type: reference
- linkId: selected-patient-gender
   variable:
   - name: selectedPatient
     language: x-fhir-query
     expression: /{{ %item.answer.valueReference.reference }}
     # expression: /{{ %QuestionnaireResponse.item.where(linkId='selected-patient-ref').answer.valueReference.reference }}
   calculatedExpression:
     language: text/fhirpath
     expression: "%selectedPatient.gender"

```
